#
# Executes commands at the start of an interactive session.
#

# Source Prezto.
if [[ -s "${ZDOTDIR:-$HOME}/.zprezto/init.zsh" ]]; then
  source "${ZDOTDIR:-$HOME}/.zprezto/init.zsh"
fi


# node 16 / latest
# export PATH="/opt/homebrew/opt/node@16/bin:/opt/homebrew/bin:usr/local/opt/libpq/bin:/usr/local/opt/libpq/bin:/usr/local/opt/ruby/bin:/opt/homebrew/opt/libpq/bin:$PATH"
export PATH="/opt/homebrew/bin:usr/local/opt/libpq/bin:/usr/local/opt/libpq/bin:/usr/local/opt/ruby/bin:/opt/homebrew/opt/libpq/bin:$PATH"

# java
export PATH="/opt/homebrew/opt/openjdk/bin:$PATH"

export PATH="$HOME/.poetry/bin:$PATH"

export NVM_DIR="$HOME/.nvm"
[ -s "$NVM_DIR/nvm.sh" ] && \. "$NVM_DIR/nvm.sh"  # This loads nvm
[ -s "$NVM_DIR/bash_completion" ] && \. "$NVM_DIR/bash_completion"  # This loads nvm bash_completion
